EconomicManagementAPP/Controllers/AccountTypesController.cs
using EconomicManagementAPP.Models;
using EconomicManagementAPP.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace EconomicManagementAPP.Controllers
{
    public class AccountTypesController : Controller
    {
        private readonly IRepositorieAccountTypes repositorieAccountTypes;
        private readonly IUserServices userServices;

        public AccountTypesController(IRepositorieAccountTypes repositorieAccountTypes,
                                      IUserServices userServices)
        {
            this.repositorieAccountTypes = repositorieAccountTypes;
            this.userServices = userServices;
        }

       
        public async Task<IActionResult> Index()
        {
            
            var userId = userServices.GetUserId();
            var accountTypes = await repositorieAccountTypes.GetAccounts(userId);
            return View(accountTypes);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AccountTypes accountTypes)
        {
            if (!ModelState.IsValid)
            {
                return View(accountTypes);
            }

            accountTypes.UserId = userServices.GetUserId();

            
            var accountTypeExist =
               await repositorieAccountTypes.Exist(accountTypes.Name, accountTypes.UserId);

            if (accountTypeExist)
            {
                
                ModelState.AddModelError(nameof(accountTypes.Name),
                    $"The account {accountTypes.Name} already exist.");

                return View(accountTypes);
            }
            await repositorieAccountTypes.Create(accountTypes);
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> VerificaryAccountType(string Name)
        {
            var UserId = userServices.GetUserId();
            var accountTypeExist = await repositorieAccountTypes.Exist(Name, UserId);

            if (accountTypeExist)
            {
                
                return Json($"The account {Name} already exist");                                                                
            }

            return Json(true);
        }

        
        [HttpGet]
        public async Task<ActionResult> Modify(int id)
        {
            var userId = userServices.GetUserId();

            var accountType = await repositorieAccountTypes.GetAccountById(id, userId);

            if (accountType is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(accountType);
        }
        [HttpPost]
        public async Task<ActionResult> Modify(AccountTypes accountTypes)
        {
            var userId = userServices.GetUserId();
            var accountType = await repositorieAccountTypes.GetAccountById(accountTypes.Id, userId);

            if (accountType is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorieAccountTypes.Modify(accountTypes);
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = userServices.GetUserId();
            var account = await repositorieAccountTypes.GetAccountById(id, userId);

            if (account is null)
            {
                return RedirectToAction("NotFount", "Home");
            }

            return View(account);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteAccount(int id)
        {
            var userId = userServices.GetUserId();
            var account = await repositorieAccountTypes.GetAccountById(id, userId);

            if (account is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var isUsed = await repositorieAccountTypes.AccountTypeIsUsed(id);

            if (isUsed)
            {
                return RedirectToAction("Error", "Home");
            }

            await repositorieAccountTypes.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

EconomicManagementAPP/Controllers/CategoriesController.cs
using AutoMapper;
using EconomicManagementAPP.Models;
using EconomicManagementAPP.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EconomicManagementAPP.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly IRepositorieCategories repositorieCategories;
        private readonly IRepositorieOperationTypes repositorieOperationTypes;
        private readonly IUserServices userServices;
        private readonly IMapper mapper;

        public CategoriesController(IRepositorieCategories repositorieCategories,
                                    IRepositorieOperationTypes repositorieOperationTypes,
                                    IUserServices userServices,
                                    IMapper mapper)
        {
            this.repositorieCategories = repositorieCategories;
            this.repositorieOperationTypes = repositorieOperationTypes;
            this.userServices = userServices;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var userId = userServices.GetUserId();
            var categorie = await repositorieCategories.GetCategories(userId);
            return View(categorie);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new CategoriesViewModel();
            model.OperationTypes = await GetOperationTypes();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Categories categorie)
        {
            var userId = userServices.GetUserId();
            categorie.UserId = userId;

            if (!ModelState.IsValid)
            {
                return View(categorie);
            }

            var categorieExist =
               await repositorieCategories.Exist(categorie.Name, userId);

            if (categorieExist)
            {
                ModelState.AddModelError(nameof(categorie.Name),
                    $"The categorie {categorie.Name} already exist.");

                return View(categorie);
            }
            await repositorieCategories.Create(categorie);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> VerificaryCategorie(string Name)
        {
            var UserId = 1;
            var categorieExist = await repositorieCategories.Exist(Name, UserId);

            if (categorieExist)
            {
                return Json($"The categorie {Name} already exist");
            }

            return Json(true);
        }

        [HttpGet]
        public async Task<ActionResult> Modify(int id)
        {
            var userId = userServices.GetUserId();
            var categorie = await repositorieCategories.GetCategorieById(id, userId);

            if (categorie is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var model = mapper.Map<CategoriesViewModel>(categorie);
            model.OperationTypes = await GetOperationTypes();

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Modify(Categories categorie)
        {
            var userId = userServices.GetUserId();
            var categorieExists = await repositorieCategories.GetCategorieById(categorie.Id, userId);

            if (categorieExists is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorieCategories.Modify(categorie);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = userServices.GetUserId();
            var categorie = await repositorieCategories.GetCategorieById(id, userId);

            if (categorie is null)
            {
                return RedirectToAction("NotFount", "Home");
            }

            return View(categorie);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAccount(int id)
        {
            var userId = userServices.GetUserId();
            var categorie = await repositorieCategories.GetCategorieById(id, userId);

            if (categorie is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            var isUsed = await repositorieCategories.CategorieIsUsed(id);
            if (isUsed)
            {
                return RedirectToAction("Error", "Home");
            }

            await repositorieCategories.Delete(id);
            return RedirectToAction("Index");
        }
        //Lista de Tipos de operacion
        private async Task<IEnumerable<SelectListItem>> GetOperationTypes() 
        {
            var operationTypes = await repositorieOperationTypes.GetOperationTypes();
            return operationTypes.Select(x => new SelectListItem(x.Description, x.Id.ToString()));
        }
    }
}

EconomicManagementAPP/Controllers/UsersController.cs
using EconomicManagementAPP.Models;
using EconomicManagementAPP.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace EconomicManagementAPP.Controllers
{
    public class UsersController : Controller
    {
        private readonly IRepositorieUsers repositorieUsers;
        private readonly UserManager<Users> userManager;
        private readonly SignInManager<Users> signInManager;

        public UsersController(IRepositorieUsers repositorieUsers,
                               UserManager<Users> userManager,
                               SignInManager<Users> signInManager)
        {
            this.repositorieUsers = repositorieUsers;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [AllowAnonymous]
        public IActionResult SignUp()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> SignUp(Users user)
        {
            if (!ModelState.IsValid)
            {
                return View(user);
            }

            var userExist =
               await repositorieUsers.Exist(user.Email);

            if (userExist)
            {
                ModelState.AddModelError(nameof(user.Email),
                    $"Email already use.");

                return View(user);
            }

            var result = await userManager.CreateAsync(user, password: user.Password);
            if(result.Succeeded)
            {
                await signInManager.SignInAsync(user, isPersistent: true);
                return RedirectToAction("Index", "Transactions");
            }

            return View(user);
        }

        //Actualizar
        [HttpGet]
        public async Task<ActionResult> Modify(int id)
        {
            var user = await repositorieUsers.GetUserById(id);

            if (user is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            return View(user);
        }
        [HttpPost]
        public async Task<ActionResult> Modify(Users user)
        {
            var userExists = await repositorieUsers.GetUserById(user.Id);

            if (userExists is null)
            {
                return RedirectToAction("NotFound", "Home");
            }

            await repositorieUsers.Modify(user);
            return RedirectToAction("Index");
        }

        //Permite que usuarios no identificados puedan ejecutar le metodo
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Login()
        {   
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel user) 
        {
            if(!ModelState.IsValid)
            {
                return View(user);
            }

            var result = await signInManager.PasswordSignInAsync(user.Email, user.Password, user.Remember, lockoutOnFailure: false);
            
            if(!result.Succeeded)
            {
                ModelState.AddModelError(string.Empty, "Wrong Email or Password");
                return View(user);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            return RedirectToAction("Login");
        }
    }
}

EconomicManagementAPP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EconomicManagementAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EconomicManagementAPP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EconomicManagementAPP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ms-auto">
                        <partial name="_LinksLogin" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EconomicManagementAPP
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EconomicManagementAPP/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Users> SignInManager
<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            @*apuntamos al controller asp-controller="AccountTypes" y al view asp-action="Index"*@
            <a class="nav-link text-dark" asp-area="" asp-controller="AccountTypes" asp-action="Index">Account Types</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-action="Logout" asp-controller="Users">
                <button type="submit" class="nav-link btn btn-link text-dark">
                    Logout
                </button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="Users" asp-action="Login">
                Login
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="Users" asp-action="SignUp">
                Sign Up
            </a>
        </li>
    }
</ul>